name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3  # Uses the checkout action

     - name: Setup Python
       uses: actions/setup-python@v4  # Uses the setup-python action
       with:
        python-version: '3.10'

     - name: Install dependencies
       run: |  # Uses the run key for multi-line commands
          python -m pip install --upgrade pip
          pip install requirements.txt

     - name: Run tests
       run: python manage.py test  # Uses the run key

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: Deploy to server (placeholder)
        run: echo "Deployment steps here-hello world Allen Chiu"  # Uses the run key for placeholder